(function(){return this['module']['require']("../../js/panda/Image.js","../../js/panda/Message.js","../../js/panda/UI.js","../../js/panda/ColorData.js","../../js/panda/Pixel.js","../../js/panda/Canvas.js","../../js/panda/ColorButton.js",dtlbind(this,function(){
var self=this;var 自分=self;
this['画面幅']=(500);
this['画面高さ']=(350);
this['画像パス']="../../image/";
this['ファイル名']="panda1-q1-150.png";
this['正解メッセージ番号']=(3);
this['画像の幅']=(1042);
this['画像の高さ']=(720);
this['横の拡大倍率']=(this['画面幅']/this['画像の幅']);
this['縦の拡大倍率']=(this['画面高さ']/this['画像の高さ']);
this['ピクセルの幅']=(23);
this['ピクセルの高さ']=(23);
this['ピクセルの横間隔']=(25);
this['ピクセルの縦間隔']=(25);
this['座標辞書']=this['辞書']['作る']();
this['座標辞書']['書く']("1?x",(((-(250)+(200))+(2))));
this['座標辞書']['書く']("2?x",(((-(250)+(200))+((this['ピクセルの横間隔']*(1))))));
this['座標辞書']['書く']("3?x",(((-(250)+(200))+((this['ピクセルの横間隔']*(2))))));
this['座標辞書']['書く']("4?x",(((-(250)+(200))+((this['ピクセルの横間隔']*(3))))));
this['座標辞書']['書く']("?1y",(((((175)-(60))-(1.5))-((this['ピクセルの縦間隔']*(0))))));
this['座標辞書']['書く']("?2y",(((((175)-(60))-(0.5))-((this['ピクセルの縦間隔']*(1))))));
this['座標辞書']['書く']("?3y",(((((175)-(60))-(0.5))-((this['ピクセルの縦間隔']*(2))))));
this['座標辞書']['書く']("?4y",(((((175)-(60))-(0.5))-((this['ピクセルの縦間隔']*(3))))));
this['座標辞書']['書く']("?5y",(((((175)-(60))-(0))-((this['ピクセルの縦間隔']*(4))))));
this['座標辞書']['書く']("?6y",(((((175)-(60))-(0))-((this['ピクセルの縦間隔']*(5))))));
this['座標辞書']['書く']("?7y",(((((175)-(60))+(0.5))-((this['ピクセルの縦間隔']*(6))))));
this['座標辞書']['書く']("1?w",(this['ピクセルの幅']));
this['座標辞書']['書く']("2?w",((this['ピクセルの幅']+(1.5))));
this['座標辞書']['書く']("3?w",((this['ピクセルの幅']+(1.5))));
this['座標辞書']['書く']("4?w",(this['ピクセルの幅']));
this['座標辞書']['書く']("?1h",((this['ピクセルの高さ']+(0.8))));
this['座標辞書']['書く']("?2h",((this['ピクセルの高さ']+(1.5))));
this['座標辞書']['書く']("?3h",((this['ピクセルの高さ']+(1.5))));
this['座標辞書']['書く']("?4h",((this['ピクセルの高さ']+(1.5))));
this['座標辞書']['書く']("?5h",((this['ピクセルの高さ']+(2))));
this['座標辞書']['書く']("?6h",((this['ピクセルの高さ']+(1))));
this['座標辞書']['書く']("?7h",((this['ピクセルの高さ']+(0.5))));
this['じっこうボタンの幅']=(130);
this['じっこうボタンのx座標']=(-(5)-(root['じっこうボタンの幅']));
this['じっこうボタンのy座標']=-(97);
this['やりなおしボタンの幅']=(130);
this['やりなおしボタンのx座標']=(5);
this['やりなおしボタンのy座標']=-(97);
this['画面配置']['実行']();
this['ピクセルの色']="black";
this['色ボタンの幅']=(32);
this['色ボタンの高さ']=(32);
this['色ボタン同士の間隔']=(4);
this['色ボタンの開始位置x']=((-this['色ボタンの幅']*(3))-(this['色ボタン同士の間隔']*(2.5)));
this['色ボタンの開始位置y']=(164);
this['色ボタン配置']['実行']();
root['縦のピクセル数']=(7);
root['横のピクセル数']=(4);
root['色データ配列']=this['配列']['作る']();
root['色データ配列']['書く']("1,2,1");
root['色データ配列']['書く']("0,1,2,1");
root['色データ配列']['書く']("3,1");
root['色データ配列']['書く']("2,1,1");
root['色データ配列']['書く']("1,1,2");
root['色データ配列']['書く']("0,1,3");
root['色データ配列']['書く']("0,4");
this['キャンバス']['表示']();
root['window']['document']['addEventListener']("touchstart",(dtlbind(this,function(e){
var self=this;var 自分=self;
return dtlbind(this,function(){
var self=this;var 自分=self;
return (root['flag']===root['真']);
})['なら']()['実行'](dtlbind(this,function(){
var self=this;var 自分=self;
return e['preventDefault']();
}));
})['bind']((this))));
return root['window']['document']['addEventListener']("touchend",(dtlbind(this,function(){
var self=this;var 自分=self;
root['flag']=root['真'];
return root['window']['setTimeout']((dtlbind(this,function(){
var self=this;var 自分=self;
return root['flag']=root['偽'];
})['bind']((this))),(400));
})['bind']((this))));
}));
}).checkerror().apply(root,[]);
//# sourceMappingURL=Panda_easy1.js.map
